### PR TITLE
When we set option complete_attributes or validation, it will also enable load_ext_dtd + doc updates

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
Reopen #47

### CODE REVIEW

**Comment by thibaultduponchelle** [comment]
@gregoa

**Comment by thibaultduponchelle** [comment]
This PR now contains #69 (+ some more doc updates) and extends to validation.

Concerning validation, the behavior is aligned to `xmllint` where `--valid` is activating the load of external DTD.

**Comment by thibaultduponchelle** [comment]
According to me, this is *the right way*. 

Having changed the defaults for security concerns is good but introduced some traps and breaking changes (since people are relying on default values that have changed, and I propose to set them implicitly in some cases, *implictly*... but not behind users back!).

If you still hesitate, `xmllint` is aligned to this:
* `--dtdattr` is doing `--loaddtd` + `--dtdattr`
* `--valid` is doing `--valid` + `--loaddtd`

**Comment by thibaultduponchelle** [comment]
Hello @Grinnz 

@shlomif advised to include you in this discussion, could you kindly please bring your expertise on this change?

Thank you a lot in advance 👍🏼 😃

**Comment by Grinnz** [comment]
Sorry, I don't know anything about DTD validation or what is appropriate in configuration

**Pull request closed without merging**
