### PR TITLE
Allow to parse XML Schema without accessing network

### PR DESCRIPTION
**Pull request by pali**
New optional parameter "no_network => 1" may be added to
XML::LibXML::Schema->new() constructor to disallow network
access when parsing supplied XML Schema.

Disabling network access when parsing XML is needed to prevent
security related problems and also to ensure that for parsing
is not needed internet connection.

### CODE REVIEW

**Comment by pali** [comment]
Testing on Travis is fixed by forcing of usage Ubuntu 14.04 on Travis. Tests are now passing.

**Comment by shlomif** [comment]
> Testing on Travis is fixed by forcing of usage Ubuntu 14.04 on Travis. Tests are now passing.

Ubuntu 14.04 is old, and I don't want to test using it. Please switch Travis to use 18.05 - possibly by removing old versions of perl. Thanks!

**Comment by pali** [comment]
> possibly by removing old versions of perl.

Done. Old perl versions were removed from .travis.yml.

**Comment by pali** [comment]
See also https://travis-ci.community/t/failure-with-perl-5-16-5-18-5-20/2458/2
> We do not compile these for Xenial. If you need these Perl versions, please use Trusty.

**Comment by pali** [comment]
https://docs.travis-ci.com/user/reference/xenial#perl-support
> Supported versions `5.22`, `5.24`, `5.26`, `5.28` and `5.30` can be installed by using the `perl:`-key.

**Comment by shlomif** [comment]
Merged now, thanks.

**Pull request closed without merging**
