### PR TITLE
Fix bug Node::replaceChild

### PR DESCRIPTION
**Pull request by Mipu94**
Fix bug us after free in XML::LibXML::Node::replaceChild.
Here is my [test](https://github.com/shlomif/perl-XML-LibXML/files/1141583/test.txt) file.
Ref: https://rt.cpan.org/Public/Bug/Display.html?id=122246

### CODE REVIEW

**Comment by Mipu94** [comment]
Hi Shlomi Fish,
I added a regression test. Can you review it?

**Comment by shlomif** [comment]
On Thu, 13 Jul 2017 04:54:21 +0000 (UTC)
sungta <notifications@github.com> wrote:

> Hi Shlomi Fish,
> I added a regression test. Can you review it?
> 

Yes, let me see.

**Comment by ppisar** [comment]
This returning NULL means an error. replaceChild() will return undef, replaceNode() will croak. While someone can consider replacing with the same node an error, I think idemponent shortcut as implemented in [https://rt.cpan.org/Public/Bug/Display.html?id=122246] is better.

**Comment by Mipu94** [comment]
Yes, that patch better than mine :D

**Comment by shlomif** [comment]
@Mipu94: yes, please make another commit with a test. Sorry for the late reply.

**Comment by shlomif** [comment]
@Mipu94 : ping!

**Comment by Mipu94** [comment]
Hi Shlomif, I'm busy in this time. I will try commit ASAP. sorry for late reply.

**Comment by shlomif** [comment]
On Sun, 15 Oct 2017 05:51:07 +0000 (UTC)
sungta <notifications@github.com> wrote:

> Hi Shlomif, I'm busy in this time. I will try commit ASAP. sorry for late
> reply.
> 

Thanks for letting me know.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Interview with Ben Collins-Sussman - http://shlom.in/sussman

Windows Update doesn’t.
    — http://www.shlomifish.org/humour/bits/facts/Windows-Update/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by Mipu94** [comment]
I just made new commit.

**Comment by shlomif** [comment]
@Mipu94 : thanks - I'm going to check it.

**Comment by shlomif** [comment]
Merged, thanks! There was some trailing space and bad formatting - I fixed them.

**Pull request merged**
