### PR TITLE
Switch to XSLoader

### PR DESCRIPTION
**Pull request by atoomic**
tested via https://github.com/atoomic/perl-XML-LibXML/actions/runs/348386427

### CODE REVIEW

**Comment by toddr** [comment]
We patch XML::LibXML to use the lighter XSLoader in our perl. We're including the patch in case you want to use it.

**Comment by shlomif** [comment]
On Thu, 05 Nov 2020 15:48:04 -0800
Todd Rinaldo <notifications@github.com> wrote:

> We patch XML::LibXML to use the lighter XSLoader in our perl. We're including
> the patch in case you want to use it.
> 

Thanks Todd and Nicholas. I'll try to review this pullreq soon.

-- 

Shlomi Fish       https://www.shlomifish.org/
Funny Anti-Terrorism Story - https://shlom.in/enemy

Chuck Norris’s cat does not chase mice. It chases dogs.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by atoomic** [comment]
Thanks @shlomif, you 🚀

**Comment by shlomif** [comment]
Merged. thanks!

**Pull request closed without merging**
