### PR TITLE
Fix setNamespace to set the empty namespace correctly

### PR DESCRIPTION
**Pull request by choroba**

### CODE REVIEW

**Comment by shlomif** [comment]
Hi @choroba ! thanks for your contribution. Please revise like this:

1. Convert it to <<return $self ... ? 1 : 0;>> - in two places

2. Add https://metacpan.org/pod/Test::Count "# TEST" annotations to the new assertions.

Thanks!

**Comment by choroba** [comment]
I created two fixups. If you're OK with them, I'll squash them.

**Comment by shlomif** [comment]
@choroba : looks good - go ahead. Thanks!

**Comment by choroba** [comment]
Done.

**Comment by shlomif** [comment]
Merged, thanks!

**Pull request merged**
