### PR TITLE
Use Alien::Libxml2.

### PR DESCRIPTION
**Pull request by genio**
Use the logic within Alien::Libxml2 to build against LibXML instead of trying to figure all of that out on our own.

This required quite a bit of reworking of our Makefile.PL file:
* Re-gathered all prereqs and got rid of any checks for Perl < 5.8 as we require Encode and utf8 which require 5.8+.
* Listed all prereqs in each category and told the Makefile.PL to merge or remove them depending on the version of MakeMaker
* No more use of inc/Devel/Checklib.pm

The Makefile.PL script should now be MUCH easier to read.

Removed `inc/Devel/CheckLib.pm` from the MANIFEST
Added `t/00-report-prereqs.t` to provide a prerequisites report

### CODE REVIEW

**Comment by genio** [comment]
The extra addition to the CI config of installing Alien::Libxml2 first was simply because we don't have a `META.json` in the dist to help `cpanm` find Config and Build prereqs. So, the `cpanm --installdeps -n .` couldn't run the Makefile.PL to find out what the prereqs were in order to install them.

This won't be a problem on shipping because a shipped dist will contain the META.json file which tells of configure/build time prereqs.

**Comment by genio** [comment]
I'll be working with others to figure out the build failure on Windows.

**Comment by shlomif** [comment]
@genio : thanks! The changes look good modulo the appveyor failure.

**Comment by plicease** [comment]
I believe that `Alien::Libxml2` version 0.06 should resolve the appveyor failure.

**Comment by shlomif** [comment]
On Fri, 22 Mar 2019 21:22:58 -0700
Graham✈️✈️ <notifications@github.com> wrote:

> I believe that `Alien::Libxml2` version 0.06 should resolve the appveyor
> failure.
> 

Thanks! I've scheduled a rebuild.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Chuck Norris/etc. Facts - http://www.shlomifish.org/humour/bits/facts/

Right to bear arms? In Soviet Russia, we have right to whole bear.
    — http://is.gd/EU4puV

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Merged, thanks!

**Pull request merged**
