### PR TITLE
fix for cperl strict hashpairs

### PR DESCRIPTION
**Pull request by rurban**
fatal under use strict since v5.27.0c.
    See https://github.com/perl11/cperl/issues/281
    and http://perl11.org/blog/strict-hashpairs.html

    With map only a missing or a single pair is allowed to construct a hash, not
    multiple pairs.

### CODE REVIEW

**Comment by shlomif** [comment]
Please see my comment on https://github.com/shlomif/perl-XML-LibXML/pull/16 - item 2 and comply.

**Comment by rurban** [comment]
The missing `make docs` is your problem. Haven't touched that.
The MSVC breakage is even worse. All the pTHX_ aTHX_ args are missing.

**Comment by shlomif** [comment]
again, Please see my comment on https://github.com/shlomif/perl-XML-LibXML/pull/16 - item no. 2 there and comply. thanks!

**Comment by shlomif** [comment]
Closing due to lack of compliance.

**Pull request closed without merging**
